print(2)
print('fail')
raise Exception("fail")